### ISSUE TITLE
[Question] Why is there no webpack dev server for this boilerplate ?

### ISSUE THREAD

**Issue by anto-christo** [madlabsinc/mevn-graphql-boilerplate#27]
Hi,
Unlike the other boilerplates provided by mevn-cli, this particular boilerplate does not have any webpack config setup in the client section. There is no dev script as well.
Hence, when `mevn run:client` is executed, there is an error thrown saying no dev script was found.

I do not have any experience with graphql and would like to know the following:

Was the webpack part skipped due to some reason or is it pending to be added? How are we supposed to get this boilerplate up and running using the mevn-cli ?

Thank you.

**Comment by jamesgeorge007** [comment]
@anto-christo Made couple of changes in the project structure. Let me know if it works fine now :+1:

**Comment by anto-christo** [comment]
Thanks @jamesgeorge007, `mevn run:client` is working now :+1:
